### ISSUE TITLE
Feature request - Being able to customize styles

### ISSUE THREAD

**Issue by geoffreycrofte** [geoffreycrofte/bluesky-social-plugin-for-wordpress#3]
- Requested by: @christophe971
- Request URL: https://wordpress.org/support/topic/bluesky-connexion-issue/#post-18249691

----
Request message:
> it was a bit tricky to find all the classes, so adding styling options in the UI would definitely be easier. Here is what I added (not a developer!):

```css
div.bluesky-social-integration-post-content-text,
span.bluesky-social-integration-post-account-info-name,
span.bluesky-social-integration-post-account-info-handle,
span.bluesky-social-integration-post-account-info-date,
p.bluesky-social-integration-external-content-title,
p.bluesky-social-integration-external-content-description,
p.bluesky-social-integration-external-content-url {
    font-size: 10px;
    line-height: 1.2em;
}
```

Suggestion: start with only font size and line-height to avoid theming issues.
